version: "3.4"
services:
  nopcommerce_web:
    build: .
    container_name: nopcommerce
    ports:
      - "8080:80"
    networks:
      - nginx-net
    depends_on:
      - nopcommerce_database
    volumes:
      - nopcommerce_data:/app
  nopcommerce_database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: nopcommerce_mssql
    networks:
      - nginx-net
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - /root/mserver-data/29-01-2023:/var/opt/mssql

volumes:
  nopcommerce_data:


networks:
  nginx-net:
    name: nhatcam-network
